# Generated by Django 4.2.6 on 2024-01-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='picture',
            field=models.ImageField(null=True, upload_to='scrappics'),
        ),
        migrations.AlterField(
            model_name='scraps',
            name='status',
            field=models.CharField(choices=[('Buynow', 'Buynow'), ('Soldout', 'Soldout')], default='pending', max_length=200),
        ),
    ]
