# Generated by Django 4.2.6 on 2024-01-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0002_alter_scraps_picture_alter_scraps_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='status',
            field=models.CharField(choices=[('Buynow', 'Buynow'), ('Soldout', 'Soldout')], default='Buynow', max_length=200),
        ),
    ]
