# Generated by Django 4.2.6 on 2024-01-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0003_alter_scraps_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Soldout', 'Soldout')], default='Available', max_length=200),
        ),
    ]
