# Generated by Django 4.2.7 on 2024-01-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0005_userprofile_wishlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='status',
            field=models.CharField(choices=[('reject', 'reject'), ('pending', 'pending'), ('accept', 'accept')], default='pending', max_length=200),
        ),
    ]
