# Generated by Django 4.2.6 on 2024-01-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0006_alter_bids_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=200),
        ),
    ]
